analyzer_rules:
- unused_import

excluded:
- Archive
- Assets

opt_in_rules:
- array_init
- contains_over_first_not_nil
- empty_count
- empty_string
- explicit_init
- fatal_error_message
- first_where
- force_unwrapping
- function_default_parameter_at_end
- implicitly_unwrapped_optional
- last_where
- lower_acl_than_parent
- multiline_function_chains
- multiline_parameters
- multiline_parameters_brackets
- multiple_closures_with_trailing_closure
- private_action
- private_outlet
- static_operator
- switch_case_on_newline
- toggle_bool
- unneeded_break_in_switch
- unused_enumerated
- unused_optional_binding
- unused_setter_value
- vertical_parameter_alignment
- vertical_parameter_alignment_on_call
- void_return
- weak_delegate
- xctfail_message
- xct_specific_matcher
- yoda_condition

disabled_rules:
- multiline_function_chains
- todo

trailing_whitespace:
    ignores_empty_lines: true
  
identifier_name:
    excluded:
        - id

function_body_length:
    warning: 50
    
line_length:
    warning: 200
